name: Docker Run Action Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          image: docker:20.10.3
          run: |
            echo "::set-output name=image_name::`uname -r`"
      - uses: actions/github-script@v3
        with:
          script: |
            console.log(core.getOutput('image_name'))
